/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    docs: Doc;
    releases: Release;
    roadmaps: Roadmap;
    benchmarks: Benchmark;
    decisions: Decision;
    pages: Page;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    roadmaps: RoadmapsSelect<false> | RoadmapsSelect<true>;
    benchmarks: BenchmarksSelect<false> | BenchmarksSelect<true>;
    decisions: DecisionsSelect<false> | DecisionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'tr') | ('en' | 'tr')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'tr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * URL and folder name. Lowercase, no spaces.
   */
  slug: string;
  name: string;
  /**
   * One line, on the card and under the name.
   */
  tagline: string;
  /**
   * Meta description. Falls back to the tagline.
   */
  description?: string | null;
  /**
   * Light mode, #rrggbb. Needs 4.5:1 on pale.
   */
  accent: string;
  /**
   * Dark mode. The lighter of the two.
   */
  accentDark?: string | null;
  monogram: string;
  /**
   * Name from src/lib/icons.mjs. Beats the monogram.
   */
  glyph?: string | null;
  status: 'active' | 'stable' | 'maintenance' | 'experiment' | 'archived';
  /**
   * Path relative to the project file, e.g. ../../_assets/x-cover.svg
   */
  cover?: string | null;
  /**
   * Index card art. Falls back to the cover.
   */
  card?: string | null;
  /**
   * Square image. Beats the glyph.
   */
  icon?: string | null;
  repo?: string | null;
  homepage?: string | null;
  license?: string | null;
  started?: string | null;
  /**
   * Names the icon set knows get a mark: Go, Docker, PostgreSQL…
   */
  stack?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pins the order and hides anything left out. Empty means "every section that has content".
   */
  sections?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Markdown. Directives, code fence options and $math$ all work as on the site.
   */
  body?: string | null;
  sources?:
    | {
        title: string;
        author?: string | null;
        url?: string | null;
        /**
         * Year, pages, chapter — free text.
         */
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  featured?: boolean | null;
  /**
   * Visible while developing, absent from the build.
   */
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  project: number | Project;
  /**
   * readme · architecture · structure · state · learned — or any id of your own.
   */
  section: string;
  /**
   * Only needed for an id the translations do not cover.
   */
  title?: string | null;
  /**
   * Tab mark. Built-in ids already have one.
   */
  glyph?: string | null;
  description?: string | null;
  order?: number | null;
  /**
   * Markdown. Directives, code fence options and $math$ all work as on the site.
   */
  body?: string | null;
  sources?:
    | {
        title: string;
        author?: string | null;
        url?: string | null;
        /**
         * Year, pages, chapter — free text.
         */
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Visible while developing, absent from the build.
   */
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  project: number | Project;
  version: string;
  date: string;
  kind: 'major' | 'minor' | 'patch' | 'prerelease';
  /**
   * One line. This is what the feed and the RSS item show.
   */
  summary: string;
  /**
   * Pinned to the top and labelled "Unreleased".
   */
  unreleased?: boolean | null;
  /**
   * Markdown. Directives, code fence options and $math$ all work as on the site.
   */
  body?: string | null;
  /**
   * Visible while developing, absent from the build.
   */
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmaps".
 */
export interface Roadmap {
  id: number;
  project: number | Project;
  updated?: string | null;
  milestones?:
    | {
        title: string;
        status: 'shipped' | 'building' | 'planned' | 'exploring';
        /**
         * Free text: "2026 Q4", "after 1.0".
         */
        target?: string | null;
        note?: string | null;
        items?:
          | {
              text: string;
              done?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Markdown. Directives, code fence options and $math$ all work as on the site.
   */
  body?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benchmarks".
 */
export interface Benchmark {
  id: number;
  project: number | Project;
  updated?: string | null;
  environment: {
    machine: string;
    os?: string | null;
    toolchain?: string | null;
    input?: string | null;
    /**
     * Runs, warm-up, and what is reported — median, p99, mean.
     */
    method: string;
  };
  suites?:
    | {
        title: string;
        /**
         * ms, MB, ops/s
         */
        unit: string;
        /**
         * Off for throughput.
         */
        lowerIsBetter?: boolean | null;
        note?: string | null;
        /**
         * At least two — a benchmark against nothing is a number.
         */
        results?:
          | {
              label: string;
              value: number;
              /**
               * This project
               */
              mine?: boolean | null;
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Markdown. Directives, code fence options and $math$ all work as on the site.
   */
  body?: string | null;
  sources?:
    | {
        title: string;
        author?: string | null;
        url?: string | null;
        /**
         * Year, pages, chapter — free text.
         */
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Visible while developing, absent from the build.
   */
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decisions".
 */
export interface Decision {
  id: number;
  project: number | Project;
  number: number;
  date: string;
  status: 'proposed' | 'accepted' | 'superseded' | 'reverted';
  title: string;
  /**
   * Numbers this record replaces.
   */
  supersedes?:
    | {
        value: number;
        id?: string | null;
      }[]
    | null;
  /**
   * The number that replaced this one.
   */
  supersededBy?: number | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Markdown. Directives, code fence options and $math$ all work as on the site.
   */
  body?: string | null;
  sources?:
    | {
        title: string;
        author?: string | null;
        url?: string | null;
        /**
         * Year, pages, chapter — free text.
         */
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Visible while developing, absent from the build.
   */
  draft?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug: string;
  title: string;
  description?: string | null;
  /**
   * Markdown. Directives, code fence options and $math$ all work as on the site.
   */
  body?: string | null;
  sources?:
    | {
        title: string;
        author?: string | null;
        url?: string | null;
        /**
         * Year, pages, chapter — free text.
         */
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'roadmaps';
        value: number | Roadmap;
      } | null)
    | ({
        relationTo: 'benchmarks';
        value: number | Benchmark;
      } | null)
    | ({
        relationTo: 'decisions';
        value: number | Decision;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  tagline?: T;
  description?: T;
  accent?: T;
  accentDark?: T;
  monogram?: T;
  glyph?: T;
  status?: T;
  cover?: T;
  card?: T;
  icon?: T;
  repo?: T;
  homepage?: T;
  license?: T;
  started?: T;
  stack?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        value?: T;
        id?: T;
      };
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        author?: T;
        url?: T;
        detail?: T;
        id?: T;
      };
  order?: T;
  featured?: T;
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  project?: T;
  section?: T;
  title?: T;
  glyph?: T;
  description?: T;
  order?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        author?: T;
        url?: T;
        detail?: T;
        id?: T;
      };
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  project?: T;
  version?: T;
  date?: T;
  kind?: T;
  summary?: T;
  unreleased?: T;
  body?: T;
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmaps_select".
 */
export interface RoadmapsSelect<T extends boolean = true> {
  project?: T;
  updated?: T;
  milestones?:
    | T
    | {
        title?: T;
        status?: T;
        target?: T;
        note?: T;
        items?:
          | T
          | {
              text?: T;
              done?: T;
              id?: T;
            };
        id?: T;
      };
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benchmarks_select".
 */
export interface BenchmarksSelect<T extends boolean = true> {
  project?: T;
  updated?: T;
  environment?:
    | T
    | {
        machine?: T;
        os?: T;
        toolchain?: T;
        input?: T;
        method?: T;
      };
  suites?:
    | T
    | {
        title?: T;
        unit?: T;
        lowerIsBetter?: T;
        note?: T;
        results?:
          | T
          | {
              label?: T;
              value?: T;
              mine?: T;
              note?: T;
              id?: T;
            };
        id?: T;
      };
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        author?: T;
        url?: T;
        detail?: T;
        id?: T;
      };
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decisions_select".
 */
export interface DecisionsSelect<T extends boolean = true> {
  project?: T;
  number?: T;
  date?: T;
  status?: T;
  title?: T;
  supersedes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  supersededBy?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        author?: T;
        url?: T;
        detail?: T;
        id?: T;
      };
  draft?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  body?: T;
  sources?:
    | T
    | {
        title?: T;
        author?: T;
        url?: T;
        detail?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}